name: VehicleGarage
version: '${project.version}'
main: nl.thebathduck.vehiclegarage.VehicleGarage
author: TheBathDuck
softdepend: [HolographicDisplays, WorldGuard, MTVehicles]
commands:
  garage: {}
  garagelocation: {}
  impound: {}